ServerEvents.tags('fluid', e => {
    e.add('forge:crude_oil', 'tfmg:crude_oil_fluid')
    e.add('forge:heavy_oil', 'tfmg:heavy_oil')
    e.add('forge:gasoline', 'tfmg:gasoline')
    e.add('forge:lpg', 'tfmg:lpg')
    e.add('forge:lpg', 'pneumaticcraft:lpg')
    e.add('forge:molten_plastic', 'tfmg:liquid_plastic')
    e.add('forge:kerosene', 'tfmg:kerosene')
    e.add('forge:naphtha', 'tfmg:naphtha')
    e.add('forge:napalm', 'tfmg:napalm')
    e.add('forge:creosote', 'tfmg:creosote')
    e.add('forge:molten_plastic', 'pneumaticcraft:plastic_flowing')
    e.add('forge:molten_plastic', 'tfmg:liquid_plastic')
    })