const whitelist = {
  "minecraft:piston": true,
  "minecraft:sticky_piston": true,
  "minecraft:repeater": true,
  "minecraft:comparator": true,
  "minecraft:dispenser": true,
  "minecraft:dropper": true,
  "minecraft:hopper": true,
  "minecraft:observer": true,
  "thermal:machine_furnace": true,
  "thermal:machine_sawmill": true,
  "thermal:machine_pulverizer": true,
  "thermal:machine_smelter": true,
  "thermal:machine_insolator": true,
  "thermal:machine_centrifuge": true,
  "thermal:machine_press": true,
  "thermal:machine_crucible": true,
  "thermal:machine_chiller": true,
  "thermal:machine_refinery": true,
  "thermal:machine_pyrolyzer": true,
  "thermal:machine_bottler": true,
  "thermal:machine_brewer": true,
  "thermal:machine_crystallizer": true,
  "thermal:machine_crafter": true,
  "thermal:dynamo_stirling": true,
  "thermal:dynamo_compression": true,
  "thermal:dynamo_magmatic": true,
  "thermal:dynamo_numismatic": true,
  "thermal:dynamo_lapidary": true,
  "thermal:dynamo_disenchantment": true,
  "thermal:dynamo_gourmand": true,
  "tfmg:diagonal_cable_block": true,
  "tfmg:blast_furnace_output": true,
  "minecraft:anvil": true,
  "minecraft:furnace": true,
  "#thermal:dynamos": true,
};
const blacklist = {
  "minecraft:hopper": "up",
};
