ServerEvents.recipes(e => {
  const entries = [
    "copper",
    "iron",
    "gold",
    "zinc",
    "tin",
    "silver",
    "lead",
    "nickel",
    "platinum",
    "aluminum",
    "chrome",
    "uranium",
    "bronze",
    "steel",
    "electrum",
    "invar",
    "constantan",
    "kanthal",
    "advanced_alloy",
    "stainless_steel",  
  ];
  // Ingots to Dusts
  entries.forEach((entry) => {
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem(`#c:ingots/${entry}`)
      .produceItem(`techpack:${entry}_dust`)
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(10)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem(`#c:ingots/${entry}`)
      .produceItem(`techpack:${entry}_dust`)
      .jei().priority(10)
  });
  e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
    .requireEnergyPerTick(40)
    .requireItem("minecraft:diamond")
    .produceItem("techpack:diamond_dust")
    .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
    .jei().priority(10)
  e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
    .requireFluidPerTick("2x techpack:steam")
    .requireItem("minecraft:diamond")
    .produceItem("techpack:diamond_dust")
    .jei().priority(10)

  //Ore blocks in steam macerator
  {
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/copper")
      .produceItem("minecraft:raw_copper")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/iron")
      .produceItem("minecraft:raw_iron")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/gold")
      .produceItem("minecraft:raw_gold")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/tin")
      .produceItem("techpack:raw_tin")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/nickel")
      .produceItem("techpack:raw_nickel")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/silver")
      .produceItem("techpack:raw_silver")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/lead")
      .produceItem("techpack:raw_lead")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/platinum")
      .produceItem("techpack:raw_platinum")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/aluminum")
      .produceItem("techpack:raw_aluminum")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/chrome")
      .produceItem("techpack:raw_chrome")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/uranium")
      .produceItem("techpack:raw_uranium")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/desh")
      .produceItem("stellaris:raw_desh_ingot")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem("#c:ores/zinc")
      .produceItem("create:raw_zinc")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem(["malum:soulstone_ore", "malum:deepslate_soulstone_ore"])
      .produceItem("malum:raw_soulstone")
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:steam_macerator", 200)
      .requireFluidPerTick("2x techpack:steam")
      .requireItem(["malum:brilliant_stone", "malum:brilliant_deepslate"])
      .produceItem("malum:raw_brilliance")
      .jei().priority(11)
  }
  //Ore blocks in basic macerator
  {
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/copper")
      .produceItem("minecraft:raw_copper")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/iron")
      .produceItem("minecraft:raw_iron")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/gold")
      .produceItem("minecraft:raw_gold")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/tin")
      .produceItem("techpack:raw_tin")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/nickel")
      .produceItem("techpack:raw_nickel")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/silver")
      .produceItem("techpack:raw_silver")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/lead")
      .produceItem("techpack:raw_lead")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/platinum")
      .produceItem("techpack:raw_platinum")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/aluminum")
      .produceItem("techpack:raw_aluminum")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/chrome")
      .produceItem("techpack:raw_chrome")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/uranium")
      .produceItem("techpack:raw_uranium")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/desh")
      .produceItem("stellaris:raw_desh_ingot")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem("#c:ores/zinc")
      .produceItem("create:raw_zinc")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem(["malum:soulstone_ore", "malum:deepslate_soulstone_ore"])
      .produceItem("malum:raw_soulstone")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
    e.recipes.custommachinery.custom_machine("techpack:basic_macerator", 200)
      .requireEnergyPerTick(20)
      .requireItem(["malum:brilliant_stone", "malum:brilliant_deepslate"])
      .produceItem("malum:raw_brilliance")
      .info(info => info.tooltip("Minimum Tier Required: Basic").item("techpack:basic_circuit"))
      .jei().priority(11)
  }
})