#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 25 09:38:26 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.6.1.zip
