	[module.energy]
		#Energy Multiplier of the Power Armor Energy Module
		# Default: 4
		# Range: > 0
		power_armor_energy_module_multiplier = 4

		[module.energy.production]
			#Energy Production of the Power Armor Solar Module
			# Default: 4
			# Range: > 0
			power_armor_solar_module_energy_production = 4

		[module.energy.usage]
			#Energy Usage of the Power Armor Night Vision Module
			# Default: 1
			# Range: > 0
			power_armor_night_vision_energy_usage = 1
			#Energy Usage of the Power Armor Jetpack Module
			# Default: 2
			# Range: > 0
			power_armor_jetpack_module_energy_usage = 2
			#Energy Usage of the Power Armor Speed Module
			# Default: 2
			# Range: > 0
			power_armor_speed_module_energy_usage = 2
			#Energy Usage of the Power Armor Plating Module
			# Default: 200
			# Range: > 0
			power_armor_plating_energy_usage = 200

	[energy.capacity]
		#Energy Capacity of the Power Armor
		# Default: 64000
		# Range: > 0
		power_armor_energy_capacity = 64000
		#Energy Capacity of the Armor Modification Table
		# Default: 256000
		# Range: > 0
		armor_modification_table_energy_capacity = 256000
		#Energy Capacity of the Battery Item
		# Default: 64000
		# Range: > 0
		battery_energy_capacity = 25000000
		#Energy Capacity of the Compressor
		# Default: 16000
		# Range: > 0
		compressor_energy_capacity = 16000

	[energy.transfer]
		#Energy Transfer of the Armor Modification Table
		# Default: 128
		# Range: > 0
		armor_modification_table_energy_transfer = 128
		#Energy Transfer of the Power Armor
		# Default: 32
		# Range: > 0
		power_armor_energy_transfer = 32
		#Energy Transfer of the Battery Item
		# Default: 32
		# Range: > 0
		battery_energy_transfer = 32
		#Energy Transfer of the Compressor
		# Default: 32
		# Range: > 0
		compressor_energy_transfer = 32

	[energy.usage]
		#Energy usage of the Compressor per tick
		# Default: 8
		# Range: > 0
		compressor_energy_usage = 8
