StartupEvents.registry("creative_mode_tab", (e) => {
  
  e.create("techlab_machines").icon(() => Item.of("custommachinery:custom_machine_item",'{machine:"custommachinery:industrialrevival/energetic_smelter"}'))

    .content(() => [
      "kubejs:basic_machine_casing",
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/generator"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/energetic_smelter"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/compressor"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/macerator"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/alloy_foundry"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/metal_former"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/assembler"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/rail_attacher"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/advanced_machines/advanced_compressor"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/advanced_machines/advanced_macerator"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/advanced_machines/advanced_alloy_foundry"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/advanced_machines/advanced_metal_former"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/advanced_machines/advanced_assembler"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/advanced_machines/advanced_rail_attacher"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/steam_turbine"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/batbox"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/cesu"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/mfe"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/mfsu"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/basic_miner"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/industrial_furnace"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/research_table"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/basic_spirit_catalyzer"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/advanced_machines/advanced_spirit_catalyzer"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/basic_storage_computer"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/fishing_basin"}'
      ),
      Item.of("custommachinery:configuration_card"),
    ]);
});
