StartupEvents.registry('block', event => {  
    //Empty Alchemy Jar
    event.create('empty_alchemy_jar')
    .displayName('Empty Alchemy Jar')
    .model('kubejs:block/alchemy_jars/empty_alchemy_jar')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Sulfur Reagent
    event.create('sulfur_reagent')
    .displayName('Sulfur Reagent')
    .model('kubejs:block/alchemy_jars/sulfur_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Niter Reagent
    event.create('niter_reagent')
    .displayName('Niter Reagent')
    .model('kubejs:block/alchemy_jars/niter_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Aluminium Reagent
    event.create('aluminium_reagent')
    .displayName('Aluminium Reagent')
    .model('kubejs:block/alchemy_jars/aluminium_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Copper Reagent
    event.create('copper_reagent')
    .displayName('Copper Reagent')
    .model('kubejs:block/alchemy_jars/copper_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Iron Reagent
    event.create('iron_reagent')
    .displayName('Iron Reagent')
    .model('kubejs:block/alchemy_jars/iron_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Zinc Reagent
    event.create('zinc_reagent')
    .displayName('Zinc Reagent')
    .model('kubejs:block/alchemy_jars/zinc_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Brass Reagent
    event.create('brass_reagent')
    .displayName('Brass Reagent')
    .model('kubejs:block/alchemy_jars/brass-_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Nickel Reagent
    event.create('nickel_reagent')
    .displayName('Nickel Reagent')
    .model('kubejs:block/alchemy_jars/nickel_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //invar Reagent
    event.create('invar_reagent')
    .displayName('invar Reagent')
    .model('kubejs:block/alchemy_jars/invar_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Amethyst Reagent
    event.create('amethyst_reagent')
    .displayName('Amethyst Reagent')
    .model('kubejs:block/alchemy_jars/amethyst_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Ferrous Pewter Reagent
    event.create('ferrous_pewter_reagent')
    .displayName('Ferrous Pewter Reagent')
    .model('kubejs:block/alchemy_jars/ferrous_pewter_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Deorum Reagent
    event.create('deorum_reagent')
    .displayName('Deorum Reagent')
    .model('kubejs:block/alchemy_jars/deorum_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
})
