StartupEvents.registry('block', event => {  
    //Empty Alchemy Jar
    event.create('empty_alchemy_jar')
    .displayName('Empty Alchemy Jar')
    .model('kubejs:block/alchemy_jars/empty_alchemy_jar')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Sulfur Reagent
    event.create('sulfur_reagent')
    .displayName('Sulfur Reagent')
    .model('kubejs:block/alchemy_jars/sulfur_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
    //Niter Reagent
    event.create('niter_reagent')
    .displayName('Niter Reagent')
    .model('kubejs:block/alchemy_jars/niter_reagent')
    .soundType('metal')
    .hardness(0.1)
    .notSolid()
    .transparent(true)
    .renderType('cutout')
    .box(.25, 0, .25, .75, 14.0 / 16.0, .75, false)
})
